feat: update distrobox to 1.7.0-1

diff --git a/distrobox-create b/distrobox-create
--- a/distrobox-create
+++ b/distrobox-create
@@ -29,6 +29,7 @@
 #	DBX_CONTAINER_IMAGE
 #	DBX_CONTAINER_MANAGER
 #	DBX_CONTAINER_NAME
+#	DBX_CONTAINER_HOSTNAME
 #	DBX_CONTAINER_GENERATE_ENTRY
 #	DBX_NON_INTERACTIVE
 #	DBX_SUDO_PROGRAM
@@ -53,12 +54,13 @@ container_clone=""
 container_generate_entry=1
 container_home_prefix=""
 container_image=""
-container_image_default="registry.fedoraproject.org/fedora-toolbox:38"
+container_image_default="registry.fedoraproject.org/fedora-toolbox:39"
 container_init_hook=""
 container_manager="autodetect"
 container_manager_additional_flags=""
 container_name=""
 container_name_default="my-distrobox"
+container_hostname=""
 container_pre_init_hook=""
 container_user_custom_home=""
 container_user_gid="$(id -rg)"
@@ -71,9 +73,11 @@ non_interactive=0
 nvidia=0
 nopasswd=0
 unshare_ipc=0
+unshare_groups=0
 unshare_netns=0
 unshare_process=0
 unshare_devsys=0
+
 # Use cd + dirname + pwd so that we do not have relative paths in mount points
 # We're not using "realpath" here so that symlinks are not resolved this way
 # "realpath" would break situations like Nix or similar symlink based package
@@ -92,12 +96,21 @@ distrobox_hostexec_path="$(cd "$(dirname "${0}")" && pwd)/distrobox-host-exec"
 # There's no need for them to pass the --root flag option in such cases.
 [ "${container_user_uid}" -eq 0 ] && rootful=1 || rootful=0
 verbose=0
-version="1.6.0.1"
+version="1.7.0"
+
+app_cache_dir=${XDG_CACHE_HOME:-"${HOME}/.cache"}/distrobox
 
 # Source configuration files, this is done in an hierarchy so local files have
 # priority over system defaults
 # leave priority to environment variables.
+#
+# On NixOS, for the distrobox derivation to pick up a static config file shipped
+# by the package maintainer the path must be relative to the script itself.
+self_dir="$(dirname "$(realpath "$0")")"
+nix_config_file="${self_dir}/../share/distrobox/distrobox.conf"
+
 config_files="
+	${nix_config_file}
 	/usr/share/distrobox/distrobox.conf
 	/usr/share/defaults/distrobox/distrobox.conf
 	/usr/etc/distrobox/distrobox.conf
@@ -110,7 +123,7 @@ for config_file in ${config_files}; do
 	# Shellcheck will give error for sourcing a variable file as it cannot follow
 	# it. We don't care so let's disable this linting for now.
 	# shellcheck disable=SC1090
-	[ -e "${config_file}" ] && . "${config_file}"
+	[ -e "${config_file}" ] && . "$(realpath "${config_file}")"
 done
 # If we're running this script as root -- as in logged in in the shell as root
 # user, and not via SUDO/DOAS --, we don't need to set distrobox_sudo_program
@@ -121,9 +134,6 @@ if [ "${container_user_uid}" -ne 0 ]; then
 	# as root (UID 0).
 	distrobox_sudo_program=${DBX_SUDO_PROGRAM:-${distrobox_sudo_program:-"sudo"}}
 fi
-# Fixup non_interactive=[true|false], in case we find it in the config file(s)
-[ "${non_interactive}" = "true" ] && non_interactive=1
-[ "${non_interactive}" = "false" ] && non_interactive=0
 
 [ -n "${DBX_CONTAINER_ALWAYS_PULL}" ] && container_always_pull="${DBX_CONTAINER_ALWAYS_PULL}"
 [ -n "${DBX_CONTAINER_CUSTOM_HOME}" ] && container_user_custom_home="${DBX_CONTAINER_CUSTOM_HOME}"
@@ -131,8 +141,17 @@ fi
 [ -n "${DBX_CONTAINER_IMAGE}" ] && container_image="${DBX_CONTAINER_IMAGE}"
 [ -n "${DBX_CONTAINER_MANAGER}" ] && container_manager="${DBX_CONTAINER_MANAGER}"
 [ -n "${DBX_CONTAINER_NAME}" ] && container_name="${DBX_CONTAINER_NAME}"
+[ -n "${DBX_CONTAINER_HOSTNAME}" ] && container_hostname="${DBX_CONTAINER_HOSTNAME}"
 [ -n "${DBX_NON_INTERACTIVE}" ] && non_interactive="${DBX_NON_INTERACTIVE}"
 [ -n "${DBX_CONTAINER_GENERATE_ENTRY}" ] && container_generate_entry="${DBX_CONTAINER_GENERATE_ENTRY}"
+[ -n "${DBX_VERBOSE}" ] && verbose="${DBX_VERBOSE}"
+
+# Fixup variable=[true|false], in case we find it in the config file(s)
+[ "${non_interactive}" = "true" ] && non_interactive=1
+[ "${non_interactive}" = "false" ] && non_interactive=0
+# Fixup variable=[true|false], in case we find it in the config file(s)
+[ "${verbose}" = "true" ] && verbose=1
+[ "${verbose}" = "false" ] && verbose=0
 
 # Print usage to stdout.
 # Arguments:
@@ -146,12 +165,12 @@ distrobox version: ${version}
 Usage:
 
 	distrobox create --image alpine:latest --name test --init-hooks "touch /var/tmp/test1 && touch /var/tmp/test2"
-	distrobox create --image fedora:38 --name test --additional-flags "--env MY_VAR-value"
-	distrobox create --image fedora:38 --name test --volume /opt/my-dir:/usr/local/my-dir:rw --additional-flags "--pids-limit -1"
+	distrobox create --image fedora:39 --name test --additional-flags "--env MY_VAR-value"
+	distrobox create --image fedora:39 --name test --volume /opt/my-dir:/usr/local/my-dir:rw --additional-flags "--pids-limit 100"
 	distrobox create -i docker.io/almalinux/8-init --init --name test --pre-init-hooks "dnf config-manager --enable powertools && dnf -y install epel-release"
-	distrobox create --clone fedora-38 --name fedora-38-copy
+	distrobox create --clone fedora-39 --name fedora-39-copy
 	distrobox create --image alpine my-alpine-container
-	distrobox create --image registry.fedoraproject.org/fedora-toolbox:38 --name fedora-toolbox-38
+	distrobox create --image registry.fedoraproject.org/fedora-toolbox:39 --name fedora-toolbox-39
 	distrobox create --pull --image centos:stream9 --home ~/distrobox/centos9
 	distrobox create --image alpine:latest --name test2 --additional-packages "git tmux vim"
 	distrobox create --image ubuntu:22.04 --name ubuntu-nvidia --nvidia
@@ -161,7 +180,8 @@ Usage:
 Options:
 
 	--image/-i:		image to use for the container	default: ${container_image_default}
-	--name/-n:		name for the distrobox		default: ${container_name_default}
+	--name/-n:		name for the distrobox          default: ${container_name_default}
+	--hostname:		hostname for the distrobox      default: <container-name>.$(uname -n)
 	--pull/-p:		pull the image even if it exists locally (implies --yes)
 	--yes/-Y:		non-interactive, pull images without asking
 	--root/-r:		launch podman/docker/lilipod with root privileges. Note that if you need root this is the preferred
@@ -178,8 +198,10 @@ Options:
 	--pre-init-hooks:	additional commands to execute prior to container initialization
 	--init/-I:		use init system (like systemd) inside the container.
 				this will make host's processes not visible from within the container. (assumes --unshare-process)
+				may require additional packages depending on the container image: https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md#using-init-system-inside-a-distrobox
 	--nvidia:		try to integrate host's nVidia drivers in the guest
 	--unshare-devsys:          do not share host devices and sysfs dirs from host
+	--unshare-groups:          do not forward user's additional groups into the container
 	--unshare-ipc:          do not share ipc namespace with host
 	--unshare-netns:        do not share the net namespace with host
 	--unshare-process:          do not share process namespace with host
@@ -209,9 +231,9 @@ EOF
 # Outputs:
 #   print usage with examples.
 show_compatibility() {
-	if [ ! -e "${HOME}/.cache/distrobox-compatibility-${version}" ] ||
-		[ ! -s "${HOME}/.cache/distrobox-compatibility-${version}" ]; then
-		mkdir -p "${HOME}/.cache"
+	if [ ! -e "${app_cache_dir}/distrobox-compatibility-${version}" ] ||
+		[ ! -s "${app_cache_dir}/distrobox-compatibility-${version}" ]; then
+		mkdir -p "${app_cache_dir}"
 
 		# If we don't have a cache file, we need connectivity. Ensure we have
 		# one and return error if not.
@@ -227,9 +249,9 @@ show_compatibility() {
 			cut -d '|' -f 4 |
 			sed 's|<br>|\n|g' |
 			tr -d ' ' |
-			sort -u > "${HOME}/.cache/distrobox-compatibility-${version}"
+			sort -u > "${app_cache_dir}/distrobox-compatibility-${version}"
 	fi
-	cat "${HOME}/.cache/distrobox-compatibility-${version}"
+	cat "${app_cache_dir}/distrobox-compatibility-${version}"
 }
 
 # Parse arguments
@@ -267,11 +289,16 @@ while :; do
 		-I | --init)
 			shift
 			init=1
+			unshare_groups=1
 			unshare_process=1
 			;;
 		--unshare-ipc)
 			shift
 			unshare_ipc=1
+			;;
+		--unshare-groups)
+			shift
+			unshare_groups=1
 			;;
 		--unshare-netns)
 			shift
@@ -287,10 +314,11 @@ while :; do
 			;;
 		--unshare-all)
 			shift
+			unshare_devsys=1
+			unshare_groups=1
 			unshare_ipc=1
 			unshare_netns=1
 			unshare_process=1
-			unshare_devsys=1
 			;;
 		-C | --compatibility)
 			show_compatibility
@@ -306,6 +334,13 @@ while :; do
 		-n | --name)
 			if [ -n "$2" ]; then
 				container_name="$2"
+				shift
+				shift
+			fi
+			;;
+		--hostname)
+			if [ -n "$2" ]; then
+				container_hostname="$2"
 				shift
 				shift
 			fi
@@ -420,19 +455,21 @@ fi
 # Examples:
 #	alpine -> alpine
 #	ubuntu:20.04 -> ubuntu-20.04
-#	registry.fedoraproject.org/fedora-toolbox:38 -> fedora-toolbox-38
+#	registry.fedoraproject.org/fedora-toolbox:39 -> fedora-toolbox-39
 #	ghcr.io/void-linux/void-linux:latest-full-x86_64 -> void-linux-latest-full-x86_64
 if [ -z "${container_name}" ]; then
 	container_name="$(basename "${container_image}" | sed -E 's/[:.]/-/g')"
 fi
 
-# container_name is later set as hostname
-# let's check if the hostname is less than 64chars or we will have problems later
-# in setting the container's hostname.
-if [ "$(printf "%s" "${container_name}.$(uname -n)" | wc -m)" -gt 64 ]; then
-	printf >&2 "ERROR: Invalid name '%s'\n" "${container_name}"
-	printf >&2 "ERROR: This will result in hostname: '%s'\n" "${container_name}.$(uname -n)"
-	printf >&2 "ERROR: Hostname too long.\n"
+# set the container hostname to default value
+if [ -z "${container_hostname}" ]; then
+	container_hostname="${container_name}.$(uname -n)"
+fi
+
+# check if container hostname is less than 64 chars to prevent issues
+if [ "$(printf "%s" "${container_hostname}" | wc -m)" -gt 64 ]; then
+	printf >&2 "ERROR: Invalid hostname '%s', longer than 64 characters\n" "${container_hostname}"
+	printf >&2 "ERROR: Use use --hostname argument to set it manually\n"
 	exit 1
 fi
 
@@ -554,11 +591,12 @@ generate_command() {
 	result_command="${container_manager} create"
 	# use the host's namespace for ipc, network, pid, ulimit
 	result_command="${result_command}
-		--hostname \"${container_name}.$(uname -n)\"
+		--hostname \"${container_hostname}\"
 		--name \"${container_name}\"
 		--privileged
 		--security-opt label=disable
 		--security-opt apparmor=unconfined
+		--pids-limit=-1
 		--user root:root"
 
 	if [ "${unshare_ipc}" -eq 0 ]; then
@@ -587,9 +625,11 @@ generate_command() {
 	# utilities.
 	result_command="${result_command}
 		--label \"manager=distrobox\"
+		--label \"distrobox.unshare_groups=${unshare_groups}\"
 		--env \"SHELL=$(basename "${SHELL:-"/bin/bash"}")\"
 		--env \"HOME=${container_user_home}\"
 		--env \"container=${container_manager}\"
+		--env \"TERMINFO_DIRS=/usr/share/terminfo:/run/host/usr/share/terminfo\"
 		--volume /:/run/host:rslave
 		--volume /tmp:/tmp:rslave
 		--volume \"${distrobox_entrypoint_path}\":/usr/bin/entrypoint:ro
@@ -689,28 +729,22 @@ generate_command() {
 	#
 	# /run/secrets is a standard location for RHEL containers, that is being pointed by
 	# /etc/rhsm-host by default.
-	if [ -e /etc/rhsm ]; then
-		result_command="${result_command}
-			--volume /etc/pki/entitlement/:/run/secrets/etc-pki-entitlement:ro
-			--volume /etc/rhsm/:/run/secrets/rhsm:ro
-			--volume /etc/yum.repos.d/redhat.repo:/run/secrets/redhat.repo:ro"
-	fi
-
-	# If we have a home prefix to use,
-	#	1- override the HOME env variable
-	#	2- export the DISTROBOX_HOST_HOME env variable pointing to original HOME
-	# 	3- mount the home inside the container.
-	if [ -n "${container_home_prefix}" ] && [ -z "${container_user_custom_home}" ]; then
-		if [ ! -d "${container_home_prefix}/${container_name}" ]; then
-			if ! mkdir -p "${container_home_prefix}/${container_name}"; then
-				printf >&2 "Do you have permission to write to %s?\n" "${container_home_prefix}"
-				exit 1
-			fi
+	RHEL_SUBSCRIPTION_FILES="
+		/etc/pki/entitlement/:/run/secrets/etc-pki-entitlement:ro
+		/etc/rhsm/:/run/secrets/rhsm:ro
+		/etc/yum.repos.d/redhat.repo:/run/secrets/redhat.repo:ro
+	"
+	for rhel_file in ${RHEL_SUBSCRIPTION_FILES}; do
+		if [ -e "$(echo "${rhel_file}" | cut -d':' -f1)" ]; then
+			result_command="${result_command}
+				--volume ${rhel_file}"
 		fi
-		result_command="${result_command}
-			--env \"HOME=${container_home_prefix}/${container_name}\"
-			--env \"DISTROBOX_HOST_HOME=${container_user_home}\"
-			--volume ${container_home_prefix}/${container_name}:${container_home_prefix}/${container_name}:rslave"
+	done
+
+	# If we have a home prefix to use, ano no custom home set, then we set
+	# the custom home to be PREFIX/CONTAINER_NAME
+	if [ -n "${container_home_prefix}" ] && [ -z "${container_user_custom_home}" ]; then
+		container_user_custom_home="${container_home_prefix}/${container_name}"
 	fi
 
 	# If we have a custom home to use,
@@ -772,8 +806,8 @@ generate_command() {
 	# container manager is podman.
 	if echo "${container_manager}" | grep -q "podman"; then
 		result_command="${result_command}
-			--ulimit host
-			--annotation run.oci.keep_original_groups=1"
+			--annotation run.oci.keep_original_groups=1
+			--ulimit host"
 
 		if [ "${init}" -eq 1 ]; then
 			result_command="${result_command}
diff --git a/distrobox-enter b/distrobox-enter
--- a/distrobox-enter
+++ b/distrobox-enter
@@ -28,10 +28,12 @@
 #	DBX_SKIP_WORKDIR
 #	DBX_SUDO_PROGRAM
 
+app_cache_dir=${XDG_CACHE_HOME:-"${HOME}/.cache"}/distrobox
+
 trap cleanup TERM INT HUP EXIT
 
 cleanup() {
-	rm -f "${HOME}/.cache/.${container_name}.fifo"
+	rm -f "${app_cache_dir}/.${container_name}.fifo"
 	if [ -n "${logs_pid:-}" ]; then
 		kill "${logs_pid:-}" 2> /dev/null || :
 	fi
@@ -54,7 +56,11 @@ fi
 
 # Defaults
 container_command=""
-container_image_default="registry.fedoraproject.org/fedora-toolbox:38"
+# by default we use getent to get the login shell of the user and use that
+container_command_login="/bin/sh -c \"\\\$(getent passwd ${USER} | cut -f 7 -d :) -l\""
+# and we execute container_command using sh -c
+container_command_prefix="/bin/sh -c"
+container_image_default="registry.fedoraproject.org/fedora-toolbox:39"
 container_manager="autodetect"
 container_manager_additional_flags=""
 container_name=""
@@ -73,12 +79,19 @@ headless=0
 [ "$(id -ru)" -eq 0 ] && rootful=1 || rootful=0
 skip_workdir=0
 verbose=0
-version="1.6.0.1"
+version="1.7.0"
 
 # Source configuration files, this is done in an hierarchy so local files have
 # priority over system defaults
 # leave priority to environment variables.
+#
+# On NixOS, for the distrobox derivation to pick up a static config file shipped
+# by the package maintainer the path must be relative to the script itself.
+self_dir="$(dirname "$(realpath "$0")")"
+nix_config_file="${self_dir}/../share/distrobox/distrobox.conf"
+
 config_files="
+	${nix_config_file}
 	/usr/share/distrobox/distrobox.conf
 	/usr/share/defaults/distrobox/distrobox.conf
 	/usr/etc/distrobox/distrobox.conf
@@ -91,7 +104,7 @@ for config_file in ${config_files}; do
 	# Shellcheck will give error for sourcing a variable file as it cannot follow
 	# it. We don't care so let's disable this linting for now.
 	# shellcheck disable=SC1090
-	[ -e "${config_file}" ] && . "${config_file}"
+	[ -e "${config_file}" ] && . "$(realpath "${config_file}")"
 done
 # If we're running this script as root -- as in, logged in in the shell as root
 # user, and not via SUDO/DOAS --, we don't need to set distrobox_sudo_program
@@ -102,14 +115,18 @@ if [ "$(id -ru)" -ne 0 ]; then
 	# as root (UID 0).
 	distrobox_sudo_program=${DBX_SUDO_PROGRAM:-${distrobox_sudo_program:-"sudo"}}
 fi
-# Fixup non_interactive=[true|false], in case we find it in the config file(s)
-[ "${non_interactive}" = "true" ] && non_interactive=1
-[ "${non_interactive}" = "false" ] && non_interactive=0
 
 [ -n "${DBX_CONTAINER_MANAGER}" ] && container_manager="${DBX_CONTAINER_MANAGER}"
 [ -n "${DBX_CONTAINER_NAME}" ] && container_name="${DBX_CONTAINER_NAME}"
 [ -n "${DBX_SKIP_WORKDIR}" ] && skip_workdir="${DBX_SKIP_WORKDIR}"
 [ -n "${DBX_NON_INTERACTIVE}" ] && non_interactive="${DBX_NON_INTERACTIVE}"
+[ -n "${DBX_VERBOSE}" ] && verbose="${DBX_VERBOSE}"
+
+# Fixup variable=[true|false], in case we find it in the config file(s)
+[ "${non_interactive}" = "true" ] && non_interactive=1
+[ "${non_interactive}" = "false" ] && non_interactive=0
+[ "${verbose}" = "true" ] && verbose=1
+[ "${verbose}" = "false" ] && verbose=0
 
 # Print usage to stdout.
 # Arguments:
@@ -122,7 +139,7 @@ distrobox version: ${version}
 
 Usage:
 
-	distrobox-enter --name fedora-38 -- bash -l
+	distrobox-enter --name fedora-39 -- bash -l
 	distrobox-enter my-alpine-container -- sh -l
 	distrobox-enter --additional-flags "--preserve-fds" --name test -- bash -l
 	distrobox-enter --additional-flags "--env MY_VAR=value" --name test -- bash -l
@@ -131,7 +148,7 @@ Usage:
 Options:
 
 	--name/-n:		name for the distrobox						default: my-distrobox
-	--/-e:			end arguments execute the rest as command to execute at login	default: bash -l
+	--/-e:			end arguments execute the rest as command to execute at login	default: default ${USER}'s shell
 	--no-tty/-T:		do not instantiate a tty
 	--no-workdir/-nw:	always start the container from container's home directory
 	--additional-flags/-a:	additional flags to pass to the container manager command
@@ -197,7 +214,6 @@ while :; do
 			;;
 		-e | --exec | --)
 			shift
-			# container_command=$*
 			container_command="$1"
 			shift
 			for arg in "$@"; do
@@ -304,8 +320,26 @@ generate_command() {
 		--interactive"
 	result_command="${result_command}
 		--detach-keys=\"\""
-	result_command="${result_command}
-		--user=\"${USER}\""
+
+	if [ "${unshare_groups:-0}" -eq 1 ]; then
+		# In case of initful systems or unshared groups, we don't enter directly
+		# as our user, but we instead enter as root, and then su $USER, in order
+		# to trigger a proper login
+		result_command="${result_command}
+			--user='root'"
+
+		# We use `su` to become the designed user, this triggers a proper login
+		# and we instantiate a proper pty with it
+		container_command_login="su ${USER}"
+		if [ "${headless}" -eq 0 ]; then
+			container_command_login="${container_command_login} --pty"
+		fi
+		container_command_login="${container_command_login} -c \"\\\$(getent passwd ${USER} | cut -f 7 -d :) -l\""
+		container_command_prefix="${container_command_login} -c"
+	else
+		result_command="${result_command}
+			--user=\"${USER}"\"
+	fi
 
 	# For some usage, like use in service, or launched by non-terminal
 	# eg. from desktop files, TTY can fail to instantiate, and fail to enter
@@ -346,7 +380,7 @@ generate_command() {
 	set +o xtrace
 	# disable logging for this snippet, or it will be too talkative.
 	for i in $(printenv | grep '=' | grep -Ev ' |"|`|\$' |
-		grep -Ev '^(HOST|HOSTNAME|HOME|PATH|PROFILEREAD|SHELL|XDG_.*_DIRS|^_)'); do
+		grep -Ev '^(CONTAINER_ID|HOST|HOSTNAME|HOME|PATH|PROFILEREAD|SHELL|XDG_SEAT|XDG_VTNR|XDG_.*_DIRS|^_)'); do
 		# We filter the environment so that we do not have strange variables,
 		# multiline or containing spaces.
 		# We also NEED to ignore the HOME variable, as this is set at create time
@@ -372,7 +406,7 @@ generate_command() {
 	done
 	# append additional standard paths to host PATH to get final container_paths
 	if [ -n "${container_paths}" ]; then
-		container_paths="${container_paths}:${PATH}"
+		container_paths="${PATH}:${container_paths}"
 	else
 		container_paths="${PATH}"
 	fi
@@ -435,12 +469,12 @@ generate_command() {
 
 	if [ -n "${container_command}" ]; then
 		result_command="${result_command}
-			${container_command}"
+			${container_command_prefix} \"${container_command}\""
 	else
 		# if no command was specified, let's execute a command that will find
 		# and run the default shell for the user
 		result_command="${result_command}
-			sh -c \"\\\$(getent passwd ${USER} | cut -f 7 -d :) -l"\"
+			${container_command_login}"
 	fi
 
 	# Return generated command.
@@ -449,6 +483,16 @@ generate_command() {
 
 container_home="${HOME}"
 container_path="${PATH}"
+unshare_groups=0
+# Now inspect the container we're working with.
+container_status="unknown"
+eval "$(${container_manager} inspect --type container --format \
+	'container_status={{.State.Status}};
+	unshare_groups={{ index .Config.Labels "distrobox.unshare_groups" }};
+	{{range .Config.Env}}{{if slice . 0 5 | eq "HOME="}}container_home={{slice . 5 | printf "%q"}};{{end}}{{end}}
+	{{range .Config.Env}}{{if slice . 0 5 | eq "PATH="}}container_path={{slice . 5 | printf "%q"}}{{end}}{{end}}' \
+	"${container_name}")"
+
 # dry run mode, just generate the command and print it. No execution.
 if [ "${dryrun}" -ne 0 ]; then
 	cmd="$(generate_command)"
@@ -456,14 +500,6 @@ if [ "${dryrun}" -ne 0 ]; then
 	printf "%s\n" "${cmd}"
 	exit 0
 fi
-
-# Now inspect the container we're working with.
-container_status="unknown"
-eval "$(${container_manager} inspect --type container --format \
-	'container_status={{.State.Status}};
-	{{range .Config.Env}}{{if slice . 0 5 | eq "HOME="}}container_home={{slice . 5 | printf "%q"}};{{end}}{{end}}
-	{{range .Config.Env}}{{if slice . 0 5 | eq "PATH="}}container_path={{slice . 5 | printf "%q"}}{{end}}{{end}}' \
-	"${container_name}")"
 
 # Check if the container is even there
 if [ "${container_status}" = "unknown" ]; then
@@ -513,6 +549,7 @@ if [ "${container_status}" != "running" ]; then
 	# Here, we save the timestamp before launching the start command, so we can
 	# be sure we're working with this very same session of logs later.
 	#
+	log_timestamp="$(date +%FT%T.%N%:z)"
 	${container_manager} start "${container_name}" > /dev/null
 	# Check if the container is going in error status earlier than the
 	# entrypoint
@@ -527,42 +564,47 @@ if [ "${container_status}" != "running" ]; then
 	fi
 
 	printf >&2 "%-40s\t" "Starting container..."
-	mkdir -p "${HOME}/.cache/"
-	rm -f "${HOME}/.cache/.${container_name}.fifo"
-	mkfifo "${HOME}/.cache/.${container_name}.fifo"
+	mkdir -p "${app_cache_dir}"
+	rm -f "${app_cache_dir}/.${container_name}.fifo"
+	mkfifo "${app_cache_dir}/.${container_name}.fifo"
 	while true; do
+		# Exit early in case of crashed/stopped container during setup
+		if [ "$(${container_manager} inspect --type container --format '{{.State.Status}}' "${container_name}")" != "running" ]; then
+			printf >&2 "\nContainer Setup Failure!\n"
+			exit 1
+		fi
 		# save starting loop timestamp in temp variable, we'll use it
 		# after to let logs command minimize possible holes
-		${container_manager} logs -f "${container_name}" 2> /dev/null \
-			> "${HOME}/.cache/.${container_name}.fifo" &
+		${container_manager} logs --since "${log_timestamp}" -f "${container_name}" 2> /dev/null \
+			> "${app_cache_dir}/.${container_name}.fifo" &
 		logs_pid="$!"
 
 		# read logs from log_timestamp to now, line by line
 		while IFS= read -r line; do
 			case "${line}" in
-				*"Error:"*)
+				"Error:"*)
 					printf >&2 "\033[31m %s\n\033[0m" "${line}"
 					exit 1
 					;;
-				*"Warning:"*)
+				"Warning:"*)
 					printf >&2 "\n\033[33m %s\033[0m" "${line}"
 					;;
-				*"distrobox:"*)
+				"distrobox:"*)
 					current_line="$(echo "${line}" | cut -d' ' -f2-)"
 					# Save current line in the status, to avoid printing the same line multiple times
 					printf >&2 "\033[32m [ OK ]\n\033[0m%-40s\t" "${current_line}"
 					;;
-				*"container_setup_done"*)
+				"container_setup_done"*)
 					printf >&2 "\033[32m [ OK ]\n\033[0m"
 					kill "${logs_pid}" > /dev/null 2>&1
 					break 2
 					;;
 				*) ;;
 			esac
-		done < "${HOME}/.cache/.${container_name}.fifo"
+		done < "${app_cache_dir}/.${container_name}.fifo"
 	done
 	# cleanup fifo
-	rm -f "${HOME}/.cache/.${container_name}.fifo"
+	rm -f "${app_cache_dir}/.${container_name}.fifo"
 	printf >&2 "\nContainer Setup Complete!\n"
 fi
 
