feat: update distrobox to 1.8.0-1

diff --git a/distrobox-create b/distrobox-create
--- a/distrobox-create
+++ b/distrobox-create
@@ -32,6 +32,7 @@
 #	DBX_CONTAINER_HOSTNAME
 #	DBX_CONTAINER_GENERATE_ENTRY
 #	DBX_NON_INTERACTIVE
+#	DBX_VERBOSE
 #	DBX_SUDO_PROGRAM
 
 # Despite of running this script via SUDO/DOAS being not supported (the
@@ -40,11 +41,18 @@
 # containers.
 #
 # SUDO_USER is a variable set by SUDO and can be used to check whether the script was called by it. Same thing for DOAS_USER, set by DOAS.
-if { [ -n "${SUDO_USER}" ] || [ -n "${DOAS_USER}" ]; } && [ "$(id -ru)" -eq 0 ]; then
+if {
+	[ -n "${SUDO_USER}" ] || [ -n "${DOAS_USER}" ]
+} && [ "$(id -ru)" -eq 0 ]; then
 	printf >&2 "Running %s via SUDO/DOAS is not supported. Instead, please try running:\n" "$(basename "${0}")"
 	printf >&2 "  %s --root %s\n" "$(basename "${0}")" "$*"
 	exit 1
 fi
+
+# Ensure we have our env variables correctly set
+[ -z "${USER}" ] && USER="$(id -run)"
+[ -z "${HOME}" ] && HOME="$(getent passwd "${USER}" | cut -d':' -f6)"
+[ -z "${SHELL}" ] && SHELL="$(getent passwd "${USER}" | cut -d':' -f7)"
 
 # Defaults
 container_additional_packages=""
@@ -54,7 +62,7 @@ container_clone=""
 container_generate_entry=1
 container_home_prefix=""
 container_image=""
-container_image_default="registry.fedoraproject.org/fedora-toolbox:39"
+container_image_default="registry.fedoraproject.org/fedora-toolbox:latest"
 container_init_hook=""
 container_manager="autodetect"
 container_manager_additional_flags=""
@@ -96,7 +104,7 @@ distrobox_hostexec_path="$(cd "$(dirname "${0}")" && pwd)/distrobox-host-exec"
 # There's no need for them to pass the --root flag option in such cases.
 [ "${container_user_uid}" -eq 0 ] && rootful=1 || rootful=0
 verbose=0
-version="1.7.0"
+version="1.8.0"
 
 app_cache_dir=${XDG_CACHE_HOME:-"${HOME}/.cache"}/distrobox
 
@@ -142,23 +150,29 @@ fi
 [ -n "${DBX_CONTAINER_MANAGER}" ] && container_manager="${DBX_CONTAINER_MANAGER}"
 [ -n "${DBX_CONTAINER_NAME}" ] && container_name="${DBX_CONTAINER_NAME}"
 [ -n "${DBX_CONTAINER_HOSTNAME}" ] && container_hostname="${DBX_CONTAINER_HOSTNAME}"
-[ -n "${DBX_NON_INTERACTIVE}" ] && non_interactive="${DBX_NON_INTERACTIVE}"
 [ -n "${DBX_CONTAINER_GENERATE_ENTRY}" ] && container_generate_entry="${DBX_CONTAINER_GENERATE_ENTRY}"
+[ -n "${DBX_NON_INTERACTIVE}" ] && non_interactive="${DBX_NON_INTERACTIVE}"
 [ -n "${DBX_VERBOSE}" ] && verbose="${DBX_VERBOSE}"
 
 # Fixup variable=[true|false], in case we find it in the config file(s)
 [ "${non_interactive}" = "true" ] && non_interactive=1
 [ "${non_interactive}" = "false" ] && non_interactive=0
-# Fixup variable=[true|false], in case we find it in the config file(s)
 [ "${verbose}" = "true" ] && verbose=1
 [ "${verbose}" = "false" ] && verbose=0
 
-# Print usage to stdout.
+# show_help will print usage to stdout.
 # Arguments:
+#   None
+# Expected global variables:
+#   version: string distrobox version
+#   container_image_default: string default container image to use
+#   container_name_default:  string default container name to use
+# Expected env variables:
 #   None
 # Outputs:
 #   print usage with examples.
-show_help() {
+show_help()
+{
 	cat << EOF
 distrobox version: ${version}
 
@@ -170,7 +184,7 @@ Usage:
 	distrobox create -i docker.io/almalinux/8-init --init --name test --pre-init-hooks "dnf config-manager --enable powertools && dnf -y install epel-release"
 	distrobox create --clone fedora-39 --name fedora-39-copy
 	distrobox create --image alpine my-alpine-container
-	distrobox create --image registry.fedoraproject.org/fedora-toolbox:39 --name fedora-toolbox-39
+	distrobox create --image registry.fedoraproject.org/fedora-toolbox:latest --name fedora-toolbox-latest
 	distrobox create --pull --image centos:stream9 --home ~/distrobox/centos9
 	distrobox create --image alpine:latest --name test2 --additional-packages "git tmux vim"
 	distrobox create --image ubuntu:22.04 --name ubuntu-nvidia --nvidia
@@ -181,7 +195,7 @@ Options:
 
 	--image/-i:		image to use for the container	default: ${container_image_default}
 	--name/-n:		name for the distrobox          default: ${container_name_default}
-	--hostname:		hostname for the distrobox      default: <container-name>.$(uname -n)
+	--hostname:		hostname for the distrobox      default: $(uname -n)
 	--pull/-p:		pull the image even if it exists locally (implies --yes)
 	--yes/-Y:		non-interactive, pull images without asking
 	--root/-r:		launch podman/docker/lilipod with root privileges. Note that if you need root this is the preferred
@@ -194,8 +208,8 @@ Options:
 	--volume:		additional volumes to add to the container
 	--additional-flags/-a:	additional flags to pass to the container manager command
 	--additional-packages/-ap:	additional packages to install during initial container setup
-	--init-hooks:		additional commands to execute during container initialization
-	--pre-init-hooks:	additional commands to execute prior to container initialization
+	--init-hooks:		additional commands to execute at the end of container initialization
+	--pre-init-hooks:	additional commands to execute at the start of container initialization
 	--init/-I:		use init system (like systemd) inside the container.
 				this will make host's processes not visible from within the container. (assumes --unshare-process)
 				may require additional packages depending on the container image: https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md#using-init-system-inside-a-distrobox
@@ -225,12 +239,18 @@ Compatibility:
 EOF
 }
 
-# Print list of compatible images to stdou, caching locally in a file.
+# show_compatibility will print the list of compatible images to stdout, caching locally in a file.
 # Arguments:
+#   None
+# Expected global variables:
+#   app_cache_dir: cache dir to write to
+#   version:       distrobox version
+# Expected env variables:
 #   None
 # Outputs:
 #   print usage with examples.
-show_compatibility() {
+show_compatibility()
+{
 	if [ ! -e "${app_cache_dir}/distrobox-compatibility-${version}" ] ||
 		[ ! -s "${app_cache_dir}/distrobox-compatibility-${version}" ]; then
 		mkdir -p "${app_cache_dir}"
@@ -354,7 +374,8 @@ while :; do
 			;;
 		-H | --home)
 			if [ -n "$2" ]; then
-				container_user_custom_home="$2"
+				# Remove trailing slashes
+				container_user_custom_home="$(echo "$2" | sed 's:/*$::')"
 				shift
 				shift
 			fi
@@ -463,7 +484,11 @@ fi
 
 # set the container hostname to default value
 if [ -z "${container_hostname}" ]; then
-	container_hostname="${container_name}.$(uname -n)"
+	container_hostname="$(uname -n)"
+
+	if [ "${unshare_netns}" -eq 1 ]; then
+		container_hostname="${container_name}.${container_hostname}"
+	fi
 fi
 
 # check if container hostname is less than 64 chars to prevent issues
@@ -540,12 +565,26 @@ if [ -n "${container_additional_volumes}" ]; then
 	done
 fi
 
-# Clone a container as a snapshot.
+# Check that we have a complete distrobox installation or
+# entrypoint and export will not work.
+if [ -z "${distrobox_entrypoint_path}" ] || [ -z "${distrobox_export_path}" ]; then
+	printf >&2 "Error: no distrobox-init found in %s\n" "${PATH}"
+	exit 127
+fi
+
+# get_clone_image will return the image name of a cloned existing container taken
+# as input.
 # Arguments:
+#   None
+# Expected global variables:
+#   container_manager: string container manager to use
+#   container_clone: string container name to clone
+# Expected env variables:
 #   None
 # Outputs:
 #   prints the image name of the newly cloned container
-clone_container() {
+get_clone_image()
+{
 	# We need to clone a container.
 	# to do this we will commit the container and create a new tag. Then use it
 	# as image for the new container.
@@ -581,12 +620,38 @@ clone_container() {
 	return 0
 }
 
-# Generate Podman or Docker command to execute.
+# generate_create_command will produce a Podman or Docker command to execute.
 # Arguments:
+#   None
+# Expected global variables:
+#   container_manager: string container manager to use
+#   container_name: string container name
+#   container_image: string container image
+#   container_manager_additional_flags: string container manager additional flags to use
+#   container_hostname: string container hostname
+#   container_additional_packages: string additional packages
+#   container_pre_init_hook: string pre init hooks
+#   container_init_hook: string init hooks
+#   container_user_home: string user's home path
+#   container_user_name: string user's username
+#   container_user_uid: string user's UID
+#   container_user_gid: string user's GID
+#   container_home_prefix: string container's custom home prefix
+#   container_user_custom_home: string container's custom home path
+#   init: bool initful
+#   nvidia: bool nvidia integration
+#   rootful: bool rootful
+#   unshare_devsys: bool unshare devsys
+#   unshare_groups: bool unshare groups
+#   unshare_ipc: bool unshare ipc
+#   unshare_netns: bool unshare netns
+#   unshare_process: bool unshare proc
+# Expected env variables:
 #   None
 # Outputs:
 #   prints the podman, docker or lilipod command to create the distrobox container
-generate_command() {
+generate_create_command()
+{
 	# Set the container hostname the same as the container name.
 	result_command="${container_manager} create"
 	# use the host's namespace for ipc, network, pid, ulimit
@@ -630,12 +695,45 @@ generate_command() {
 		--env \"HOME=${container_user_home}\"
 		--env \"container=${container_manager}\"
 		--env \"TERMINFO_DIRS=/usr/share/terminfo:/run/host/usr/share/terminfo\"
-		--volume /:/run/host:rslave
+		--env \"CONTAINER_ID=${container_name}\"
 		--volume /tmp:/tmp:rslave
 		--volume \"${distrobox_entrypoint_path}\":/usr/bin/entrypoint:ro
 		--volume \"${distrobox_export_path}\":/usr/bin/distrobox-export:ro
 		--volume \"${distrobox_hostexec_path}\":/usr/bin/distrobox-host-exec:ro
 		--volume \"${container_user_home}\":\"${container_user_home}\":rslave"
+
+	# Due to breaking change in https://github.com/opencontainers/runc/commit/d4b670fca6d0ac606777376440ffe49686ce15f4
+	# now we cannot mount /:/run/host as before, as it will try to mount RO partitions as RW thus breaking things.
+	# This will ensure we will mount directories one-by-one thus avoiding this problem.
+	#
+	# This happens ONLY with podman+runc, docker and lilipod are unaffected, so let's do this only if we have podman AND runc.
+	if echo "${container_manager}" | grep -q "podman" && ${container_manager} info | grep -q runc; then
+		for rootdir in /*; do
+
+			# Skip symlinks
+			if [ -L "${rootdir}" ]; then
+				continue
+			fi
+
+			# Find if the directory belongs to a RO mount, if do, mount it as RO+Rslave
+			if findmnt --notruncate --noheadings --list --output OPTIONS --target "${rootdir}" |
+				tr ',' '\n' | grep -q "^ro$"; then
+
+				result_command="${result_command}
+				--volume ${rootdir}:/run/host${rootdir}:ro,rslave"
+				continue
+			fi
+
+			# Else we mount it RW+Rslave
+			result_command="${result_command}
+				--volume ${rootdir}:/run/host${rootdir}:rslave"
+		done
+	else
+		# We're either on podman+crun, docker or lilipod, let's keep old behaviour
+		result_command="${result_command}
+			--volume /:/run/host/:rslave"
+
+	fi
 
 	if [ "${unshare_devsys}" -eq 0 ]; then
 		result_command="${result_command}
@@ -794,6 +892,13 @@ generate_command() {
 			/etc/hosts
 			/etc/resolv.conf
 		"
+
+		# If container_hostname is custom, we skip mounting /etc/hostname, else
+		# we want to keep it in sync
+		if [ "${container_hostname}" = "$(uname -n)" ]; then
+			NET_FILES="${NET_FILES} /etc/hostname"
+		fi
+
 		for net_file in ${NET_FILES}; do
 			if [ -e "${net_file}" ]; then
 				result_command="${result_command}
@@ -854,19 +959,12 @@ generate_command() {
 	printf "%s" "${result_command}"
 }
 
-# Check that we have a complete distrobox installation or
-# entrypoint and export will not work.
-if [ -z "${distrobox_entrypoint_path}" ] || [ -z "${distrobox_export_path}" ]; then
-	printf >&2 "Error: no distrobox-init found in %s\n" "${PATH}"
-	exit 127
-fi
-
 # dry run mode, just generate the command and print it. No creation.
 if [ "${dryrun}" -ne 0 ]; then
 	if [ -n "${container_clone}" ]; then
 		container_image="${container_clone}"
 	fi
-	cmd="$(generate_command)"
+	cmd="$(generate_create_command)"
 	cmd="$(echo "${cmd}" | sed 's/\t//g')"
 	printf "%s\n" "${cmd}"
 	exit 0
@@ -890,8 +988,9 @@ fi
 # if we are using the clone flag, let's set the image variable
 # to the output of container duplication
 if [ -n "${container_clone}" ]; then
-	container_image="$(clone_container)"
+	container_image="$(get_clone_image)"
 fi
+
 # First, check if the image exists in the host or auto-pull is enabled
 # If not prompt to download it.
 if [ "${container_always_pull}" -eq 1 ] ||
@@ -929,7 +1028,7 @@ fi
 
 # Generate the create command and run it
 printf >&2 "Creating '%s' using image %s\t" "${container_name}" "${container_image}"
-cmd="$(generate_command)"
+cmd="$(generate_create_command)"
 # Eval the generated command. If successful display an helpful message.
 # shellcheck disable=SC2086
 if eval ${cmd} > /dev/null; then
@@ -949,6 +1048,8 @@ if eval ${cmd} > /dev/null; then
 			"${distrobox_genentry_path}" "${container_name}"
 		fi
 	fi
-	exit $?
+else
+	error="$?"
+	printf >&2 "\033[31m [ ERR ]\033[0m failed to create container.\n"
+	exit "${error}"
 fi
-printf >&2 "\033[31m [ ERR ]\n\033[0m"
diff --git a/distrobox-export b/distrobox-export
--- a/distrobox-export
+++ b/distrobox-export
@@ -25,7 +25,14 @@
 #	DISTROBOX_ENTER_PATH
 #	DISTROBOX_HOST_HOME
 
+# Ensure we have our env variables correctly set
+[ -z "${USER}" ] && USER="$(id -run)"
+[ -z "${HOME}" ] && HOME="$(getent passwd "${USER}" | cut -d':' -f6)"
+[ -z "${SHELL}" ] && SHELL="$(getent passwd "${USER}" | cut -d':' -f7)"
+
 # Defaults
+container_name="${CONTAINER_ID:-}"
+[ -z "${container_name}" ] && container_name="$(grep "name=" /run/.containerenv | cut -d'=' -f2- | tr -d '"')"
 export_action=""
 exported_app=""
 exported_app_label=""
@@ -37,19 +44,19 @@ enter_flags=""
 #	DBX_HOST_HOME is set in case container is created
 #	with custom --home directory
 host_home="${DISTROBOX_HOST_HOME:-"${HOME}"}"
-dest_path="${host_home}/.local/bin"
+dest_path="${DISTROBOX_EXPORT_PATH:-${host_home}/.local/bin}"
 is_sudo=0
 rootful=""
 sudo_prefix=""
 verbose=0
-version="1.7.0"
+version="1.8.0"
 
 sudo_askpass_path="${dest_path}/distrobox_sudo_askpass"
 sudo_askpass_script="#!/bin/sh
 if command -v zenity 2>&1 > /dev/null; then
 	zenity --password
 elif command -v kdialog 2>&1 > /dev/null; then
-	kdialog --password
+	kdialog --password 'A password is required...'
 else
 	exit 127
 fi"
@@ -63,12 +70,17 @@ for dep in ${base_dependencies}; do
 	fi
 done
 
-# Print usage to stdout.
+# show_help will print usage to stdout.
 # Arguments:
+#   None
+# Expected global variables:
+#   version: distrobox version
+# Expected env variables:
 #   None
 # Outputs:
 #   print usage with examples.
-show_help() {
+show_help()
+{
 	cat << EOF
 distrobox version: ${version}
 
@@ -79,10 +91,10 @@ Usage:
 
 Options:
 
-	--app/-a:		name of the application to export
+	--app/-a:		name of the application to export or absolute path to desktopfile to export
 	--bin/-b:		absolute path of the binary to export
 	--list-apps:		list applications exported from this container
-	--list-binaries		list binaries exported from this container, use -ep to specify custom paths to search
+	--list-binaries:	list binaries exported from this container, use -ep to specify custom paths to search
 	--delete/-d:		delete exported application or binary
 	--export-label/-el:	label to add to exported application name.
 				Use "none" to disable.
@@ -192,6 +204,11 @@ if [ "${verbose}" -ne 0 ]; then
 	set -o xtrace
 fi
 
+# Ensure we can write stuff there
+if [ ! -e "${dest_path}" ]; then
+	mkdir -p "${dest_path}"
+fi
+
 # Check we're running inside a container and not on the host.
 if [ ! -f /run/.containerenv ] && [ ! -f /.dockerenv ] && [ -z "${container:-}" ]; then
 	printf >&2 "You must run %s inside a container!\n" " $(basename "$0")"
@@ -216,55 +233,11 @@ if [ "$(id -u)" -eq 0 ]; then
 	exit 1
 fi
 
-# Ensure the foundamental variables are set and not empty, we will not proceed
-# if they are not all set.
-if [ -z "${exported_app}" ] && [ -z "${exported_bin}" ]; then
-	printf >&2 "Error: Invalid arguments.\n"
-	printf >&2 "Error: missing export target. Run\n"
-	printf >&2 "\tdistrobox-export --help\n"
-	printf >&2 "for more information.\n"
-	exit 2
-fi
 # Ensure we're not receiving more than one action at time.
 if [ -n "${exported_app}" ] && [ -n "${exported_bin}" ]; then
 	printf >&2 "Error: Invalid arguments, choose only one action below.\n"
 	printf >&2 "Error: You can only export one thing at time.\n"
 	exit 2
-fi
-# Ensure we have the export-path set when exporting a binary.
-if [ -n "${exported_bin}" ] && [ -z "${dest_path}" ]; then
-	printf >&2 "Error: Missing argument export-path.\n"
-	exit 2
-fi
-
-if [ -n "${CONTAINER_ID}" ]; then
-	container_name="${CONTAINER_ID}"
-# if the variable is not set, let's fall back to some tricks.
-elif [ -e /.dockerenv ]; then
-	# we're in docker, let's use this trick
-	container_name=$(grep "memory:/" < /proc/self/cgroup | sed 's|.*/||')
-elif [ -e /run/.containerenv ]; then
-	# we're in podman or lilipod, use this other trick
-	container_name=$(grep "name=" /run/.containerenv | cut -d'=' -f2- | tr -d '"')
-fi
-# If one of the previous methods didn't work
-# let's fallback to a more simple way but error prone
-if [ -z "${container_name}" ]; then
-	container_name=$(uname -n | cut -d'.' -f1)
-fi
-
-# Command to execute
-container_command_suffix="${exported_bin} ${extra_flags} \"\$@\""
-
-# Check if exported application/binary should be run with sudo privileges
-if [ "${is_sudo}" -ne 0 ]; then
-	sudo_prefix="sudo -S"
-
-	# Edge case for systems without sudo
-	if command -v su-exec > /dev/null >&1; then
-		sudo_prefix="su-exec root"
-		container_command_suffix="sh -l -c \"${exported_bin} ${extra_flags} \$*\""
-	fi
 fi
 
 # Filter enter_flags and remove redundant options
@@ -291,6 +264,20 @@ if [ -n "${enter_flags}" ]; then
 	enter_flags="${filtered_flags}"
 fi
 
+# Command to execute
+container_command_suffix="'${exported_bin}' ${extra_flags} \"\$@\""
+
+# Check if exported application/binary should be run with sudo privileges
+if [ "${is_sudo}" -ne 0 ]; then
+	sudo_prefix="sudo -S"
+
+	# Edge case for systems without sudo
+	if command -v su-exec > /dev/null >&1; then
+		sudo_prefix="su-exec root"
+		container_command_suffix="sh -l -c \"'${exported_bin}' ${extra_flags} \$@\""
+	fi
+fi
+
 # Prefix to add to an existing command to work through the container
 container_command_prefix="${DISTROBOX_ENTER_PATH:-"distrobox-enter"} ${rootful} -n ${container_name} ${enter_flags} -- ${sudo_prefix} "
 
@@ -307,12 +294,27 @@ else
 	exported_app_label=" ${exported_app_label}"
 fi
 
-# Print generated script from template
+# generate_script will generate a script from template. This script will wrap the
+# exported binary in order to ensure it will be executed in the right container.
 # Arguments:
-#	none it will use the ones set up globally
+#	None
+# Expected global variables:
+#   CONTAINER_ID: id of the current container
+#   container_command_suffix: string to postpone to the command to launch
+#   container_name:  string name of this container
+#   dest_path: string path where to export the binary
+#   enter_flags:  string extra flags to append to the distrobox enter command
+#   exported_bin: string path to the binary to export
+#   exported_delete: bool delete the binary exported
+#   extra_flags:  string extra flags to append to the exported app command
+#   rootful: bool if this is a rootful container
+#   sudo_prefix: string sudo command to prepend to the exported command
+# Expected env variables:
+#   None
 # Outputs:
 #	print generated script.
-generate_script() {
+generate_script()
+{
 	cat << EOF
 #!/bin/sh
 # distrobox_binary
@@ -320,24 +322,33 @@ generate_script() {
 if [ -z "\${CONTAINER_ID}" ]; then
 	exec "${DISTROBOX_ENTER_PATH:-"distrobox-enter"}" ${rootful} -n ${container_name} ${enter_flags} -- ${sudo_prefix} ${container_command_suffix}
 elif [ -n "\${CONTAINER_ID}" ] && [ "\${CONTAINER_ID}" != "${container_name}" ]; then
-	exec distrobox-host-exec ${dest_path}/$(basename "${exported_bin}") ${extra_flags} "\$@"
+	exec distrobox-host-exec '${dest_path}/$(basename "${exported_bin}")' "\$@"
 else
-	exec ${exported_bin} "\$@"
+	exec '${exported_bin}' "\$@"
 fi
 EOF
 	return $?
 }
 
-# Export binary to destination directory.
+# export_binary will export selected binary to destination directory.
 # the following function will use generate_script to create a shell script in
 # dest_path that will execute the exported binary in the selected distrobox.
 #
 # Arguments:
-#	none it will use the ones set up globally
+#	None
+# Expected global variables:
+#   CONTAINER_ID: id of the current container
+#   container_name: string name of this container
+#   dest_path: string path where to export the binary
+#   exported_bin: string path to the binary to export
+#   exported_delete: bool delete the binary exported
+# Expected env variables:
+#   None
 # Outputs:
 #	a generated_script in dest_path
 #	or error code.
-export_binary() {
+export_binary()
+{
 	# Ensure the binary we're exporting is installed
 	if [ ! -f "${exported_bin}" ]; then
 		printf >&2 "Error: cannot find %s.\n" "${exported_bin}"
@@ -346,16 +357,23 @@ export_binary() {
 	# generate dest_file path
 	dest_file="${dest_path}/$(basename "${exported_bin}")"
 
+	# create the binary destination path if it doesn't exist
+	mkdir -p "${dest_path}"
+
 	# If we're deleting it, just do it and exit
-	if [ "${exported_delete}" -ne 0 ] &&
+	if [ "${exported_delete}" -ne 0 ]; then
 		# ensure it's a distrobox exported binary
-		grep -q "distrobox_binary" "${dest_file}"; then
+		if ! grep -q "distrobox_binary" "${dest_file}"; then
+			printf >&2 "Error: %s is not exported.\n" "${exported_bin}"
+			return 1
+		fi
 
 		if rm -f "${dest_file}"; then
 			printf "%s from %s removed successfully from %s.\nOK!\n" \
 				"${exported_bin}" "${container_name}" "${dest_path}"
 			return 0
 		fi
+		return 1
 	fi
 
 	# test if we have writing rights on the file
@@ -375,54 +393,69 @@ export_binary() {
 	return 3
 }
 
-# Export graphical application to the host.
+# export_application will export input graphical application to the host.
 # the following function will scan the distrobox for desktop and icon files for
 # the selected application. It will then put the needed icons in the host's icons
 # directory and create a new .desktop file that will execute the selected application
 # in the distrobox.
 #
 # Arguments:
-#	none it will use the ones set up globally
+#	None
+# Expected global variables:
+#   CONTAINER_ID: id of the current container
+#   container_command_prefix: string to prepend to the command to launch
+#   container_name:  string name of this container
+#   exported_app:   string name of the app to export
+#   exported_app_label: string label to use to mark the exported app
+#   exported_delete:  bool if we want to delete or not
+#   extra_flags:  string extra flags to append to the exported app command
+#   host_home: home path ofr the host, where to search desktop files
+# Expected env variables:
+#   None
 # Outputs:
 #	needed icons in /run/host/$host_home/.local/share/icons
 #	needed desktop files in /run/host/$host_home/.local/share/applications
 #	or error code.
-export_application() {
+export_application()
+{
 	canon_dirs=""
 
-	IFS=":"
-	if [ -n "${XDG_DATA_DIRS}" ]; then
-		for xdg_data_home in ${XDG_DATA_HOME}; do
-			[ -d "${xdg_data_home}/applications" ] && canon_dirs="${canon_dirs} ${xdg_data_home}/applications"
-		done
+	# In case we're explicitly going for a full desktopfile path
+	if [ -e "${exported_app}" ]; then
+		desktop_files="${exported_app}"
 	else
-		[ -d /usr/share/applications ] && canon_dirs="/usr/share/applications"
-		[ -d /usr/local/share/applications ] && canon_dirs="${canon_dirs} /usr/local/share/applications"
-		[ -d /var/lib/flatpak/exports/share/applications ] && canon_dirs="${canon_dirs} /var/lib/flatpak/exports/share/applications"
-	fi
-	if [ -n "${XDG_DATA_HOME}" ]; then
-		for xdg_data_dir in ${XDG_DATA_DIRS}; do
-			[ -d "${xdg_data_dir}/applications" ] && canon_dirs="${canon_dirs} ${xdg_data_dir}/applications"
-		done
-	else
-		[ -d "${HOME}/.local/share/applications" ] && canon_dirs="${canon_dirs} ${HOME}/.local/share/applications"
-	fi
-	unset IFS
+		IFS=":"
+		if [ -n "${XDG_DATA_DIRS}" ]; then
+			for xdg_data_dir in ${XDG_DATA_DIRS}; do
+				[ -d "${xdg_data_dir}/applications" ] && canon_dirs="${canon_dirs} ${xdg_data_dir}/applications"
+			done
+		else
+			[ -d /usr/share/applications ] && canon_dirs="/usr/share/applications"
+			[ -d /usr/local/share/applications ] && canon_dirs="${canon_dirs} /usr/local/share/applications"
+			[ -d /var/lib/flatpak/exports/share/applications ] && canon_dirs="${canon_dirs} /var/lib/flatpak/exports/share/applications"
+		fi
+		if [ -n "${XDG_DATA_HOME}" ]; then
+			[ -d "${XDG_DATA_HOME}/applications" ] && canon_dirs="${canon_dirs} ${XDG_DATA_HOME}/applications"
+		else
+			[ -d "${HOME}/.local/share/applications" ] && canon_dirs="${canon_dirs} ${HOME}/.local/share/applications"
+		fi
+		unset IFS
 
-	# In this phase we search for applications to export.
-	# First find command will grep through all files in the canonical directories
-	# and only list files that contain the $exported_app, excluding those that
-	# already contains a distrobox-enter command. So skipping already exported apps.
-	# Second find will list all files that contain the name specified, so that
-	# it is possible to export an app not only by its executable name but also
-	# by its launcher name.
-	desktop_files=$(
-		# shellcheck disable=SC2086
-		find ${canon_dirs} -type f -print -o -type l -print | sed 's/./\\&/g' |
-			xargs -I{} grep -l -e "Exec=.*${exported_app}.*" -e "Name=.*${exported_app}.*" "{}" | sed 's/./\\&/g' |
-			xargs -I{} grep -L -e "Exec=.*${DISTROBOX_ENTER_PATH:-"distrobox.*enter"}.*" "{}" | sed 's/./\\&/g' |
-			xargs -I{} printf "%s@" "{}"
-	)
+		# In this phase we search for applications to export.
+		# First find command will grep through all files in the canonical directories
+		# and only list files that contain the $exported_app, excluding those that
+		# already contains a distrobox-enter command. So skipping already exported apps.
+		# Second find will list all files that contain the name specified, so that
+		# it is possible to export an app not only by its executable name but also
+		# by its launcher name.
+		desktop_files=$(
+			# shellcheck disable=SC2086
+			find ${canon_dirs} -type f -print -o -type l -print | sed 's/./\\&/g' |
+				xargs -I{} grep -l -e "Exec=.*${exported_app}.*" -e "Name=.*${exported_app}.*" "{}" | sed 's/./\\&/g' |
+				xargs -I{} grep -L -e "Exec=.*${DISTROBOX_ENTER_PATH:-"distrobox.*enter"}.*" "{}" | sed 's/./\\&/g' |
+				xargs -I{} printf "%s¤" "{}"
+		)
+	fi
 
 	# Ensure the app we're exporting is installed
 	# Check that we found some desktop files first.
@@ -435,30 +468,31 @@ export_application() {
 	# Find icons by using the Icon= specification. If it's only a name, we'll
 	# search for the file, if it's already a path, just grab it.
 	icon_files=""
-	IFS="@"
+	IFS="¤"
 	for desktop_file in ${desktop_files}; do
 		if [ -z "${desktop_file}" ]; then
 			continue
 		fi
 
-		icon_name="$(grep Icon= "${desktop_file}" | cut -d'=' -f2- | paste -sd "@" -)"
+		icon_name="$(grep Icon= "${desktop_file}" | cut -d'=' -f2- | paste -sd "¤" -)"
 
 		for icon in ${icon_name}; do
-			if [ -e "${icon_name}" ]; then
+			if case "${icon_name}" in "/"*) true ;; *) false ;; esac &&
+				[ -e "${icon_name}" ]; then
 				# In case it's an hard path, conserve it and continue
-				icon_files="${icon_files}@${icon_name}"
+				icon_files="${icon_files}¤${icon_name}"
 			else
 				# If it's not an hard path, find all files in the canonical paths.
-				icon_files="${icon_files}@$(find \
+				icon_files="${icon_files}¤$(find \
 					/usr/share/icons \
 					/usr/share/pixmaps \
 					/var/lib/flatpak/exports/share/icons -iname "*${icon}*" \
-					-printf "%p@" 2> /dev/null || :)"
+					-printf "%p¤" 2> /dev/null || :)"
 			fi
 		done
 
 		# remove leading delimiter
-		icon_files=${icon_files#@}
+		icon_files=${icon_files#¤}
 	done
 
 	# create applications dir if not existing
@@ -466,7 +500,7 @@ export_application() {
 
 	# copy icons in home directory
 	icon_file_absolute_path=""
-	IFS="@"
+	IFS="¤"
 	for icon_file in ${icon_files}; do
 		if [ -z "${icon_file}" ]; then
 			continue
@@ -499,7 +533,7 @@ export_application() {
 	done
 
 	# create desktop files for the distrobox
-	IFS="@"
+	IFS="¤"
 	for desktop_file in ${desktop_files}; do
 		if [ -z "${desktop_file}" ]; then
 			continue
@@ -562,18 +596,23 @@ export_application() {
 		printf "Application %s successfully exported.\nOK!\n" "${exported_app}"
 		printf "%s will appear in your applications list in a few seconds.\n" "${exported_app}"
 	fi
-
 }
 
-# List exported applications in canonical directories.
+# list_exported_applications will print all exported applications in canonical directories.
 # the following function will list exported desktop files from this container.
 #
 # Arguments:
-#	none
+#	None
+# Expected global variables:
+#   host_home: home path ofr the host, where to search desktop files
+#   CONTAINER_ID: id of the current container
+# Expected env variables:
+#   None
 # Outputs:
 #	a list of exported apps
 #	or error code.
-list_exported_applications() {
+list_exported_applications()
+{
 	# In this phase we search for applications exported.
 	# First find command will grep through all files in the canonical directories
 	# and only list files that contain the $DISTROBOX_ENTER_PATH.
@@ -581,12 +620,15 @@ list_exported_applications() {
 		# shellcheck disable=SC2086
 		find "/run/host${host_home}/.local/share/applications" -type f -print -o -type l -print 2> /dev/null | sed 's/./\\&/g' |
 			xargs -I{} grep -l -e "Exec=.*${DISTROBOX_ENTER_PATH:-"distrobox.*enter"}.*" "{}" | sed 's/./\\&/g' |
-			xargs -I{} printf "%s@" "{}"
+			xargs -I{} printf "%s¤" "{}"
 	)
 
 	# Then we try to pretty print them.
-	IFS="@"
+	IFS="¤"
 	for i in ${desktop_files}; do
+		if [ -z "${i}" ]; then
+			continue
+		fi
 		# Get app name, and remove label
 		name="$(grep -Eo 'Name=.*' "${i}" | head -n 1 | cut -d'=' -f2- | sed 's|(.*)||g')"
 		# Print only stuff we exported from this box!
@@ -594,30 +636,40 @@ list_exported_applications() {
 			printf "%-20s | %-30s\n" "${name}" "${i}"
 		fi
 	done
+	unset IFS
 }
 
-# List exported binaries.
+# list_exported_binaries will print all exported binaries.
 # the following function will list exported desktop files from this container.
 # If no export-path is specified, it searches in the default path.
 #
 # Arguments:
-#	none
+#	None
+# Expected global variables:
+#   dest_path: destination path where to search binaries
+#   CONTAINER_ID: id of the current container
+# Expected env variables:
+#	None
 # Outputs:
 #	a list of exported apps
 #	or error code.
-list_exported_binaries() {
+list_exported_binaries()
+{
 	# In this phase we search for binaries exported.
 	# First find command will grep through all files in the canonical directories
 	# and only list files that contain the comment "# distrobox_binary".
 	binary_files=$(
 		find "${dest_path}" -type f -print 2> /dev/null | sed 's/./\\&/g' |
 			xargs -I{} grep -l -e "^# distrobox_binary" "{}" | sed 's/./\\&/g' |
-			xargs -I{} printf "%s@" "{}"
+			xargs -I{} printf "%s¤" "{}"
 	)
 
 	# Then we try to pretty print them.
-	IFS="@"
+	IFS="¤"
 	for i in ${binary_files}; do
+		if [ -z "${i}" ]; then
+			continue
+		fi
 		# Get original binary name
 		name="$(grep -B1 "fi" "${i}" | grep exec | cut -d' ' -f2)"
 		# Print only stuff we exported from this box!
@@ -625,6 +677,7 @@ list_exported_binaries() {
 			printf "%-20s | %-30s\n" "${name}" "${i}"
 		fi
 	done
+	unset IFS
 }
 
 # Main routine
diff --git a/distrobox-rm b/distrobox-rm
--- a/distrobox-rm
+++ b/distrobox-rm
@@ -24,6 +24,7 @@
 #	DBX_CONTAINER_NAME
 #	DBX_CONTAINER_RM_CUSTOM_HOME
 #	DBX_NON_INTERACTIVE
+#	DBX_VERBOSE
 #	DBX_SUDO_PROGRAM
 
 # Despite of running this script via SUDO/DOAS being not supported (the
@@ -32,11 +33,18 @@
 # containers.
 #
 # SUDO_USER is a variable set by SUDO and can be used to check whether the script was called by it. Same thing for DOAS_USER, set by DOAS.
-if { [ -n "${SUDO_USER}" ] || [ -n "${DOAS_USER}" ]; } && [ "$(id -ru)" -eq 0 ]; then
+if {
+	[ -n "${SUDO_USER}" ] || [ -n "${DOAS_USER}" ]
+} && [ "$(id -ru)" -eq 0 ]; then
 	printf >&2 "Running %s via SUDO/DOAS is not supported. Instead, please try running:\n" "$(basename "${0}")"
 	printf >&2 "  %s --root %s\n" "$(basename "${0}")" "$*"
 	exit 1
 fi
+
+# Ensure we have our env variables correctly set
+[ -z "${USER}" ] && USER="$(id -run)"
+[ -z "${HOME}" ] && HOME="$(getent passwd "${USER}" | cut -d':' -f6)"
+[ -z "${SHELL}" ] && SHELL="$(getent passwd "${USER}" | cut -d':' -f7)"
 
 # Defaults
 all=0
@@ -52,8 +60,7 @@ non_interactive=0
 verbose=0
 rm_home=0
 response_rm_home="N"
-response_rm_exports="N"
-version="1.7.0"
+version="1.8.0"
 
 # Source configuration files, this is done in an hierarchy so local files have
 # priority over system defaults
@@ -81,9 +88,14 @@ for config_file in ${config_files}; do
 	[ -e "${config_file}" ] && . "$(realpath "${config_file}")"
 done
 
+[ -n "${DBX_CONTAINER_MANAGER}" ] && container_manager="${DBX_CONTAINER_MANAGER}"
+[ -n "${DBX_CONTAINER_RM_CUSTOM_HOME}" ] && rm_home="${DBX_CONTAINER_RM_CUSTOM_HOME}"
+[ -n "${DBX_NON_INTERACTIVE}" ] && non_interactive="${DBX_NON_INTERACTIVE}"
 [ -n "${DBX_VERBOSE}" ] && verbose="${DBX_VERBOSE}"
 
 # Fixup variable=[true|false], in case we find it in the config file(s)
+[ "${non_interactive}" = "true" ] && non_interactive=1
+[ "${non_interactive}" = "false" ] && non_interactive=0
 [ "${verbose}" = "true" ] && verbose=1
 [ "${verbose}" = "false" ] && verbose=0
 
@@ -96,25 +108,22 @@ if [ "$(id -ru)" -ne 0 ]; then
 	# as root (UID 0).
 	distrobox_sudo_program=${DBX_SUDO_PROGRAM:-${distrobox_sudo_program:-"sudo"}}
 fi
-# Fixup non_interactive=[true|false], in case we find it in the config file(s)
-[ "${non_interactive}" = "true" ] && non_interactive=1
-[ "${non_interactive}" = "false" ] && non_interactive=0
-
-[ -n "${DBX_CONTAINER_MANAGER}" ] && container_manager="${DBX_CONTAINER_MANAGER}"
-[ -n "${DBX_CONTAINER_RM_CUSTOM_HOME}" ] && rm_home="${DBX_CONTAINER_RM_CUSTOM_HOME}"
-[ -n "${DBX_NON_INTERACTIVE}" ] && non_interactive="${DBX_NON_INTERACTIVE}"
 
 # Declare it AFTER config sourcing because we do not want a default name set for rm.
-container_name=""
 container_name_default="my-distrobox"
 container_name_list=""
 
-# Print usage to stdout.
+# show_help will print usage to stdout.
 # Arguments:
+#   None
+# Expected global variables:
+#   version: distrobox version
+# Expected env variables:
 #   None
 # Outputs:
 #   print usage with examples.
-show_help() {
+show_help()
+{
 	cat << EOF
 distrobox version: ${version}
 
@@ -245,6 +254,7 @@ if ! command -v "${container_manager}" > /dev/null; then
 	printf >&2 "\thttps://github.com/89luca89/distrobox/blob/main/docs/compatibility.md\n"
 	exit 127
 fi
+
 # add verbose if -v is specified
 if [ "${verbose}" -ne 0 ]; then
 	container_manager="${container_manager} --log-level debug"
@@ -279,12 +289,62 @@ if [ -z "${container_name_list}" ]; then
 	container_name_list="${container_name_default}"
 fi
 
-# Delete containers.
+# cleanup_exports will remove exported apps and bins for container to delete.
 # Arguments:
-#   container_name
+#   container_name: string container name
+# Expected global variables:
+#   distrobox_flags: string additional distrobox flags to use
+# Expected env variables:
+#   None
 # Outputs:
-#   none.
-delete_container() {
+#   None
+cleanup_exports()
+{
+	container_name="$1"
+	IFS='¤'
+	printf "Removing exported binaries...\n"
+	binary_files="$(grep -rl "# distrobox_binary" "${HOME}/.local/bin" 2> /dev/null | sed 's/./\\&/g' |
+		xargs -I{} grep -le "# name: ${container_name}$" "{}" | sed 's/./\\&/g' |
+		xargs -I{} printf "%s¤" "{}" 2> /dev/null || :)"
+	for file in ${binary_files}; do
+		printf "Removing exported binary %s...\n" "${file}"
+		rm -f "${file}"
+	done
+
+	# Remove exported gui apps from this container in default path
+	# shellcheck disable=SC2086,SC2038
+	desktop_files="$(find "${HOME}/.local/share/applications/${container_name}"* -type f -o -type l 2> /dev/null | sed 's/./\\&/g' |
+		xargs -I{} grep -le "Exec=.*${container_name} " "{}" | sed 's/./\\&/g' |
+		xargs -I{} printf "%s¤" "{}" 2> /dev/null || :)"
+	for file in ${desktop_files}; do
+		if [ -e "${file}" ]; then
+			app="$(grep -Eo "Name=.*" "${file}" | head -n 1 | cut -d'=' -f2)"
+			icon="$(grep -Eo "Icon=.*" "${file}" | head -n 1 | cut -d'=' -f2)"
+
+			printf "Removing exported app %s...\n" "${app}"
+			rm -f "${file}"
+			find "${HOME}/.local/share/icons" -name "${icon}.*" -delete
+		fi
+	done
+	unset IFS
+}
+
+# delete_container will remove input container
+# Arguments:
+#   container_name: string container name
+# Expected global variables:
+#   container_manager: string container manager to use
+#   distrobox_flags: string distrobox additional flags
+#   non_interactive: bool non interactive mode
+#   force_flag: bool force mode
+#   rm_home: bool remove home
+#   verbose: bool verbose
+# Expected env variables:
+#   None
+# Outputs:
+#   None
+delete_container()
+{
 	container_name="$1"
 	# Inspect the container we're working with.
 	container_status="$(${container_manager} inspect --type container \
@@ -299,7 +359,7 @@ delete_container() {
 	# Retrieve container's HOME, and check if it's different from host's one. In
 	# this case we prompt for deletion of the custom home.
 	container_home=$(${container_manager} inspect --type container --format \
-		'{{range .Config.Env}}{{if slice . 0 5 | eq "HOME="}}{{slice . 5}}{{end}}{{end}}' "${container_name}")
+		'{{range .Config.Env}}{{if and (ge (len .) 5) (eq (slice . 0 5) "HOME=")}}{{slice . 5 | printf "%q"}}{{end}}{{end}}' "${container_name}")
 	# Prompt for confirmation
 	if [ "${container_home}" != "${HOME}" ]; then
 		if [ "${non_interactive}" -eq 0 ] &&
@@ -327,22 +387,13 @@ delete_container() {
 			;;
 	esac
 
-	rm_exports=0
-	if [ "${container_status}" != "running" ] && [ "${non_interactive}" -eq 0 ]; then
-		printf "Container %s not running.\n" "${container_name}"
-		printf "Do you want to start it to remove exported apps and binaries? [y/N]: "
-		read -r response_rm_exports
-		response_rm_exports="${response_rm_exports:-"N"}"
-	fi
-
-	if [ "${non_interactive}" -eq 1 ] || [ "${rm_exports}" -eq 1 ]; then
-		cleanup_exports
-	fi
-
 	# Remove the container
 	printf "Removing container...\n"
 	# shellcheck disable=SC2086,SC2248
-	${container_manager} rm ${force_flag} "${container_name}"
+	${container_manager} rm ${force_flag} --volumes "${container_name}"
+
+	# Remove exported apps and bins
+	cleanup_exports "${container_name}"
 
 	# We're going to delete the box, let's also delete the entry
 	verbose_arg=""
@@ -358,34 +409,6 @@ delete_container() {
 	fi
 }
 
-# Delete exported apps and bins for container to delete.
-# Arguments:
-#   none.
-# Outputs:
-#   none.
-cleanup_exports() {
-	IFS='
-	'
-	printf "Removing exported binaries...\n"
-	# Ensure we hide distrobox startup if not needed
-	# shellcheck disable=SC2086,2248
-	"$(dirname "$(realpath "${0}")")/distrobox-enter" ${distrobox_flags} "${container_name}" -- whoami > /dev/null 2>&1
-	# Remove exported binaries from this container in default path
-	# shellcheck disable=SC2086,2248
-	for i in $("$(dirname "$(realpath "${0}")")/distrobox-enter" ${distrobox_flags} "${container_name}" -- distrobox-export --list-binaries); do
-		bin="$(echo "${i}" | cut -d'|' -f1 | sed 's/[ ]*$//' | sed 's/^[ ]*//')"
-		dir="$(echo "${i}" | cut -d'|' -f2- | sed 's/[ ]*$//' | sed 's/^[ ]*//')"
-		# shellcheck disable=SC2086,2248
-		"$(dirname "$(realpath "${0}")")/distrobox-enter" ${distrobox_flags} "${container_name}" -- distrobox-export --bin "${bin}" --export-path "$(dirname "${dir}")" --delete
-	done
-	unset IFS
-
-	# Remove exported gui apps from this container in default path
-	# shellcheck disable=SC2086,2248
-	"$(dirname "$(realpath "${0}")")/distrobox-enter" ${distrobox_flags} "${container_name}" -- sh -c "distrobox-export --list-apps | cut -d'|' -f1 | sed 's/[ ]*$//' | xargs -I{} distrobox-export --app \"{}\" -d"
-
-}
-
 # Prompt for confirmation
 if [ "${non_interactive}" -eq 0 ] && [ "${force}" -eq 0 ]; then
 	printf "Do you really want to delete containers:%s? [Y/n]: " "${container_name_list}"
@@ -395,11 +418,38 @@ else
 	response="yes"
 fi
 
+for container in ${container_name_list}; do
+	if [ "$(${container_manager} inspect --type container --format '{{.State.Status}}' "${container}")" = "running" ]; then
+		if [ "${non_interactive}" -eq 0 ] && [ "${force}" -eq 0 ]; then
+			printf "Container %s running, do you want to force delete them? [Y/n]: " "${container_name_list}"
+			read -r response_force
+			response_force="${response_force:-"Y"}"
+		else
+			response_force="yes"
+		fi
+	fi
+
+	# Accept only y,Y,Yes,yes,n,N,No,no.
+	case "${response_force:-"N"}" in
+		y | Y | Yes | yes | YES)
+			force=1
+			force_flag="--force"
+			break
+			;;
+		n | N | No | no | NO) ;;
+
+		*) # Default case: If no more options then break out of the loop.
+			printf >&2 "Invalid input.\n"
+			printf >&2 "The available choices are: y,Y,Yes,yes,YES or n,N,No,no,NO.\nExiting.\n"
+			;;
+	esac
+done
+
 # Accept only y,Y,Yes,yes,n,N,No,no.
 case "${response}" in
 	y | Y | Yes | yes | YES)
-		for container_name in ${container_name_list}; do
-			delete_container "${container_name}"
+		for container in ${container_name_list}; do
+			delete_container "${container}"
 		done
 		;;
 	n | N | No | no | NO)
